services:
  db:
    image: postgres:15
    # image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mealbot
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend  # This tells Docker to look INSIDE the backend folder
      dockerfile: Dockerfile

  frontend:
    build: ./frontend
    ports:
      - "5173:80"  # Map host 5173 to container 80